import { describe, test, expect } from 'vitest';
import { readFileSync } from 'fs';
import { compile } from '../src/compiler.js';

const EXAMPLES = ['counter', 'todo', 'dashboard', 'chat', 'ecommerce'];
const TARGETS = ['react', 'vue', 'svelte'] as const;

function readExample(name: string): string {
  return readFileSync(`examples/${name}.ai`, 'utf-8');
}

describe('Integration Tests — Example Files', () => {
  for (const example of EXAMPLES) {
    describe(`${example}.ai`, () => {
      let source: string;

      test('파일 읽기', () => {
        source = readExample(example);
        expect(source.length).toBeGreaterThan(0);
      });

      for (const target of TARGETS) {
        test(`${target} 컴파일 성공`, () => {
          source = readExample(example);
          const result = compile(source, { target, validate: false });
          expect(result.code.length).toBeGreaterThan(0);
          expect(result.code).toContain('// Generated by 0x');
        });

        test(`${target} 코드 비어있지 않음`, () => {
          source = readExample(example);
          const result = compile(source, { target, validate: false });
          expect(result.lineCount).toBeGreaterThan(5);
        });
      }
    });
  }
});

describe('Integration Tests — Roundtrip', () => {
  test('카운터 앱 React 컴파일 — 유효한 JSX 구조', () => {
    const source = readExample('counter');
    const result = compile(source, { target: 'react', validate: false });

    // Basic structural checks
    expect(result.code).toContain('function Counter(');
    expect(result.code).toContain('useState');
    expect(result.code).toContain('useMemo');
    expect(result.code).toContain('return (');
    expect(result.code).toContain('</div>');
    expect(result.code).toContain('</button>');

    // Check balanced JSX tags
    const openDivs = (result.code.match(/<div/g) || []).length;
    const closeDivs = (result.code.match(/<\/div>/g) || []).length;
    expect(openDivs).toBe(closeDivs);
  });

  test('Todo 앱 React 컴파일 — useState, 조건부 렌더링', () => {
    const source = readExample('todo');
    const result = compile(source, { target: 'react', validate: false });
    expect(result.code).toContain('useState');
    expect(result.code).toContain('.map(');
    expect(result.code).toContain('<button');
    expect(result.code).toContain('<input');
  });

  test('대시보드 앱 Vue 컴파일 — script setup + template', () => {
    const source = readExample('dashboard');
    const result = compile(source, { target: 'vue', validate: false });
    expect(result.code).toContain('<script setup>');
    expect(result.code).toContain('<template>');
    expect(result.code).toContain('ref(');
    expect(result.code).toContain('onMounted');
  });

  test('채팅 앱 Svelte 컴파일 — $state + {#each}', () => {
    const source = readExample('chat');
    const result = compile(source, { target: 'svelte', validate: false });
    expect(result.code).toContain('$state(');
    expect(result.code).toContain('{#each');
    expect(result.code).toContain('<button');
  });

  test('이커머스 앱 3개 타겟 모두 컴파일', () => {
    const source = readExample('ecommerce');
    for (const target of TARGETS) {
      const result = compile(source, { target, validate: false });
      expect(result.code.length).toBeGreaterThan(100);
    }
  });
});

describe('Validation Integration', () => {
  test('순환 derived — 컴파일 에러', () => {
    const source = `page Bad:\n  derived a = b + 1\n  derived b = a + 1`;
    expect(() => compile(source, { target: 'react' })).toThrow(/circular/i);
  });

  test('정상적인 앱은 validation 통과', () => {
    const source = readExample('counter');
    expect(() => compile(source, { target: 'react' })).not.toThrow();
  });
});
