// 0x → Terraform HCL Generator
// Converts infrastructure AST nodes into Terraform configuration

import type {
  ASTNode, GeneratedCode, Expression,
  DeployNode, EnvNode, DockerNode, DomainNode, CdnNode,
  StorageNode, MonitorNode, BackupNode, CacheNode,
} from '../ast.js';
import { genExpr, ctx } from './react.js';

export function generateTerraform(ast: ASTNode[]): GeneratedCode {
  const providers = new Set<string>();
  const resources: string[] = [];
  const variables: string[] = [];

  for (const node of ast) {
    switch (node.type) {
      case 'Deploy':
        genDeploy(node, resources, providers);
        break;
      case 'Env':
        genEnvVars(node, variables);
        break;
      case 'Docker':
        genDocker(node, resources, providers);
        break;
      case 'Domain':
        genDomain(node, resources, providers);
        break;
      case 'Cdn':
        genCdn(node, resources, providers);
        break;
      case 'Storage':
        genStorage(node, resources, providers);
        break;
      case 'Monitor':
        genMonitor(node, resources, providers);
        break;
      case 'Backup':
        genBackup(node, resources, providers);
        break;
      case 'Cache':
        genCache(node, resources, providers);
        break;
      default:
        break;
    }
  }

  const lines: string[] = [];
  lines.push('# Generated by 0x — Terraform Configuration');
  lines.push('');

  // Terraform block with required providers
  lines.push('terraform {');
  lines.push('  required_version = ">= 1.0"');
  lines.push('  required_providers {');
  for (const p of providers) {
    const source = getProviderSource(p);
    lines.push(`    ${p} = {`);
    lines.push(`      source  = "${source}"`);
    lines.push(`    }`);
  }
  lines.push('  }');
  lines.push('}');
  lines.push('');

  // Provider configurations
  for (const p of providers) {
    lines.push(`provider "${p}" {}`);
  }
  if (providers.size > 0) lines.push('');

  // Variables
  if (variables.length > 0) {
    lines.push(...variables);
    lines.push('');
  }

  // Resources
  if (resources.length > 0) {
    lines.push(...resources);
  }

  const code = lines.join('\n');
  return {
    code,
    filename: 'main.tf',
    imports: [],
    lineCount: code.split('\n').length,
    tokenCount: code.split(/\s+/).filter(t => t.length > 0).length,
  };
}

function getProviderSource(provider: string): string {
  const sources: Record<string, string> = {
    aws: 'hashicorp/aws',
    docker: 'kreuzwerker/docker',
    vercel: 'vercel/vercel',
    cloudflare: 'cloudflare/cloudflare',
    datadog: 'DataDog/datadog',
    sentry: 'jianyuan/sentry',
  };
  return sources[provider] || `hashicorp/${provider}`;
}

function exprToHcl(expr: Expression): string {
  const c = ctx();
  const val = genExpr(expr, c);
  // Convert JS-style strings to HCL-style
  if (val.startsWith("'") && val.endsWith("'")) {
    return `"${val.slice(1, -1)}"`;
  }
  return val;
}

function propsToHcl(props: Record<string, Expression>, indent: string): string[] {
  const lines: string[] = [];
  for (const [key, expr] of Object.entries(props)) {
    const hclKey = key.replace(/([A-Z])/g, '_$1').toLowerCase();
    lines.push(`${indent}${hclKey} = ${exprToHcl(expr)}`);
  }
  return lines;
}

function genDeploy(node: DeployNode, resources: string[], providers: Set<string>): void {
  const provider = node.provider;

  if (provider === 'aws') {
    providers.add('aws');
    resources.push(`resource "aws_instance" "app" {`);
    const region = node.props['region'] ? exprToHcl(node.props['region']) : '"us-east-1"';
    resources.push(`  ami           = "ami-0c55b159cbfafe1f0"`);
    resources.push(`  instance_type = "t3.micro"`);
    for (const [k, v] of Object.entries(node.props)) {
      if (k === 'region') continue;
      resources.push(`  ${k} = ${exprToHcl(v)}`);
    }
    resources.push(`  tags = {`);
    resources.push(`    Name = "0x-app"`);
    resources.push(`  }`);
    resources.push(`}`);
    resources.push('');
  } else if (provider === 'vercel') {
    providers.add('vercel');
    resources.push(`resource "vercel_project" "app" {`);
    resources.push(`  name      = "0x-app"`);
    resources.push(`  framework = "nextjs"`);
    resources.push(...propsToHcl(node.props, '  '));
    resources.push(`}`);
    resources.push('');
  } else if (provider === 'fly') {
    providers.add('fly');
    resources.push(`resource "fly_app" "app" {`);
    resources.push(`  name = "0x-app"`);
    resources.push(...propsToHcl(node.props, '  '));
    resources.push(`}`);
    resources.push('');
  } else if (provider === 'docker') {
    providers.add('docker');
    resources.push(`resource "docker_container" "app" {`);
    resources.push(`  name  = "0x-app"`);
    resources.push(`  image = "node:20-alpine"`);
    resources.push(...propsToHcl(node.props, '  '));
    resources.push(`}`);
    resources.push('');
  } else {
    // Generic
    resources.push(`resource "null_resource" "${provider}_deploy" {`);
    resources.push(`  # Provider: ${provider}`);
    resources.push(...propsToHcl(node.props, '  '));
    resources.push(`}`);
    resources.push('');
  }
}

function genEnvVars(node: EnvNode, variables: string[]): void {
  variables.push(`# Environment: ${node.envType}`);
  for (const v of node.vars) {
    const c = ctx();
    const defVal = genExpr(v.value, c);
    variables.push(`variable "${v.name}" {`);
    if (v.secret) {
      variables.push(`  sensitive = true`);
    }
    variables.push(`  type    = string`);
    const hclDefault = defVal.startsWith("'") ? `"${defVal.slice(1, -1)}"` : defVal;
    variables.push(`  default = ${hclDefault}`);
    variables.push(`}`);
    variables.push('');
  }
}

function genDocker(node: DockerNode, resources: string[], providers: Set<string>): void {
  providers.add('docker');
  const image = node.baseImage || 'node:20-alpine';
  resources.push(`resource "docker_image" "app" {`);
  resources.push(`  name = "${image}"`);
  resources.push(`}`);
  resources.push('');
  resources.push(`resource "docker_container" "app" {`);
  resources.push(`  name  = "0x-app"`);
  resources.push(`  image = docker_image.app.image_id`);
  resources.push(...propsToHcl(node.props, '  '));
  resources.push(`  ports {`);
  resources.push(`    internal = 3000`);
  resources.push(`    external = 3000`);
  resources.push(`  }`);
  resources.push(`}`);
  resources.push('');
}

function genDomain(node: DomainNode, resources: string[], providers: Set<string>): void {
  providers.add('aws');
  resources.push(`resource "aws_route53_zone" "${sanitize(node.domain)}" {`);
  resources.push(`  name = "${node.domain}"`);
  resources.push(`}`);
  resources.push('');
  resources.push(`resource "aws_route53_record" "${sanitize(node.domain)}_a" {`);
  resources.push(`  zone_id = aws_route53_zone.${sanitize(node.domain)}.zone_id`);
  resources.push(`  name    = "${node.domain}"`);
  resources.push(`  type    = "A"`);
  resources.push(`  ttl     = 300`);
  resources.push(`  records = ["0.0.0.0"]`);
  resources.push(`}`);
  resources.push('');
  // SSL certificate
  if (node.props['ssl'] || node.props['https']) {
    resources.push(`resource "aws_acm_certificate" "${sanitize(node.domain)}" {`);
    resources.push(`  domain_name       = "${node.domain}"`);
    resources.push(`  validation_method = "DNS"`);
    resources.push(`}`);
    resources.push('');
  }
}

function genCdn(node: CdnNode, resources: string[], providers: Set<string>): void {
  if (node.provider === 'cloudflare') {
    providers.add('cloudflare');
    resources.push(`resource "cloudflare_zone" "cdn" {`);
    resources.push(`  zone = "example.com"`);
    resources.push(...propsToHcl(node.props, '  '));
    resources.push(`}`);
  } else {
    // Default: AWS CloudFront
    providers.add('aws');
    resources.push(`resource "aws_cloudfront_distribution" "cdn" {`);
    resources.push(`  enabled = true`);
    resources.push(`  origin {`);
    resources.push(`    domain_name = "origin.example.com"`);
    resources.push(`    origin_id   = "0x-origin"`);
    resources.push(`  }`);
    resources.push(`  default_cache_behavior {`);
    resources.push(`    allowed_methods  = ["GET", "HEAD"]`);
    resources.push(`    cached_methods   = ["GET", "HEAD"]`);
    resources.push(`    target_origin_id = "0x-origin"`);
    resources.push(`    viewer_protocol_policy = "redirect-to-https"`);
    resources.push(`    forwarded_values {`);
    resources.push(`      query_string = false`);
    resources.push(`      cookies { forward = "none" }`);
    resources.push(`    }`);
    resources.push(`  }`);
    resources.push(`  restrictions {`);
    resources.push(`    geo_restriction { restriction_type = "none" }`);
    resources.push(`  }`);
    resources.push(`  viewer_certificate {`);
    resources.push(`    cloudfront_default_certificate = true`);
    resources.push(`  }`);
    resources.push(`}`);
  }
  resources.push('');
}

function genStorage(node: StorageNode, resources: string[], providers: Set<string>): void {
  const c = ctx();
  const bucket = node.props['bucket'] ? exprToHcl(node.props['bucket']) : `"${node.name}"`;

  if (node.provider === 's3' || node.provider === 'r2' || !node.provider) {
    providers.add('aws');
    resources.push(`resource "aws_s3_bucket" "${node.name}" {`);
    resources.push(`  bucket = ${bucket}`);
    resources.push(`}`);
    resources.push('');
    // Versioning
    resources.push(`resource "aws_s3_bucket_versioning" "${node.name}" {`);
    resources.push(`  bucket = aws_s3_bucket.${node.name}.id`);
    resources.push(`  versioning_configuration {`);
    resources.push(`    status = "Enabled"`);
    resources.push(`  }`);
    resources.push(`}`);
    resources.push('');
  } else if (node.provider === 'gcs') {
    providers.add('google');
    resources.push(`resource "google_storage_bucket" "${node.name}" {`);
    resources.push(`  name     = ${bucket}`);
    resources.push(`  location = "US"`);
    resources.push(`}`);
    resources.push('');
  }
}

function genMonitor(node: MonitorNode, resources: string[], providers: Set<string>): void {
  if (node.provider === 'datadog') {
    providers.add('datadog');
    resources.push(`resource "datadog_monitor" "app" {`);
    resources.push(`  name    = "0x App Monitor"`);
    resources.push(`  type    = "metric alert"`);
    resources.push(`  message = "Alert: Application issue detected"`);
    resources.push(`  query   = "avg(last_5m):avg:system.cpu.user{*} > 80"`);
    resources.push(...propsToHcl(node.props, '  '));
    resources.push(`}`);
  } else if (node.provider === 'sentry') {
    providers.add('sentry');
    resources.push(`resource "sentry_project" "app" {`);
    resources.push(`  organization = "my-org"`);
    resources.push(`  team         = "my-team"`);
    resources.push(`  name         = "0x-app"`);
    resources.push(`  platform     = "node"`);
    resources.push(...propsToHcl(node.props, '  '));
    resources.push(`}`);
  } else {
    resources.push(`# Monitor: ${node.provider}`);
    resources.push(`resource "null_resource" "${node.provider}_monitor" {`);
    resources.push(...propsToHcl(node.props, '  '));
    resources.push(`}`);
  }
  resources.push('');
}

function genBackup(node: BackupNode, resources: string[], providers: Set<string>): void {
  providers.add('aws');
  resources.push(`resource "aws_backup_vault" "vault" {`);
  resources.push(`  name = "0x-backup-vault"`);
  resources.push(`}`);
  resources.push('');
  resources.push(`resource "aws_backup_plan" "plan" {`);
  resources.push(`  name = "0x-backup-plan"`);
  resources.push(`  rule {`);
  resources.push(`    rule_name         = "${node.strategy}"`);
  resources.push(`    target_vault_name = aws_backup_vault.vault.name`);

  const scheduleMap: Record<string, string> = {
    daily: 'cron(0 3 * * ? *)',
    hourly: 'cron(0 * * * ? *)',
    realtime: 'cron(0/15 * * * ? *)',
  };
  resources.push(`    schedule = "${scheduleMap[node.strategy] || scheduleMap.daily}"`);
  resources.push(`  }`);
  resources.push(`}`);
  resources.push('');
}

function genCache(node: CacheNode, resources: string[], providers: Set<string>): void {
  if (node.strategy === 'redis') {
    providers.add('aws');
    resources.push(`resource "aws_elasticache_cluster" "${node.name}" {`);
    resources.push(`  cluster_id      = "${node.name}"`);
    resources.push(`  engine          = "redis"`);
    resources.push(`  node_type       = "cache.t3.micro"`);
    resources.push(`  num_cache_nodes = 1`);
    resources.push(`  port            = 6379`);
    resources.push(`}`);
    resources.push('');
  }
}

function sanitize(s: string): string {
  return s.replace(/[^a-zA-Z0-9_]/g, '_');
}
