import { describe, test, expect } from 'vitest';
import { compile } from '../../src/compiler.js';

function compileReact(source: string): string {
  return compile(source, { target: 'react' }).code;
}

describe('React Code Generator', () => {
  describe('기본 구조', () => {
    test('빈 page → React 컴포넌트', () => {
      const output = compileReact('page Empty:');
      expect(output).toContain('// Generated by 0x');
      expect(output).toContain('export default function Empty()');
    });

    test('빈 component → React 컴포넌트', () => {
      const output = compileReact('component Card:\n  prop title: str');
      expect(output).toContain('function Card(');
    });
  });

  describe('state 변환', () => {
    test('state → useState (int)', () => {
      const output = compileReact('page T:\n  state count: int = 0');
      expect(output).toContain('const [count, setCount] = useState(0)');
      expect(output).toContain("useState");
    });

    test('state → useState (str)', () => {
      const output = compileReact('page T:\n  state name: str = ""');
      expect(output).toContain("const [name, setName] = useState('')");
    });

    test('state → useState (bool)', () => {
      const output = compileReact('page T:\n  state loading: bool = true');
      expect(output).toContain('const [loading, setLoading] = useState(true)');
    });

    test('state → useState (list)', () => {
      const output = compileReact('page T:\n  state items: list[str] = []');
      expect(output).toContain('const [items, setItems] = useState([])');
    });
  });

  describe('derived 변환', () => {
    test('derived → useMemo', () => {
      const output = compileReact('page T:\n  state a: int = 1\n  derived total = a + 1');
      expect(output).toContain('useMemo');
      expect(output).toContain('total');
    });
  });

  describe('prop 변환', () => {
    test('prop → 함수 파라미터', () => {
      const output = compileReact('component C:\n  prop title: str\n  prop size: int = 16');
      expect(output).toContain('title');
      expect(output).toContain('size');
    });
  });

  describe('함수 변환', () => {
    test('fn → useCallback', () => {
      const output = compileReact('page T:\n  state count: int = 0\n  fn increment():\n    count += 1');
      expect(output).toContain('increment');
      expect(output).toContain('setCount');
    });

    test('async fn', () => {
      const output = compileReact('page T:\n  async fn load():\n    result = await fetch("/api")');
      expect(output).toContain('async');
      expect(output).toContain('await');
    });
  });

  describe('라이프사이클', () => {
    test('on mount → useEffect', () => {
      const output = compileReact('page T:\n  on mount:\n    loading = false');
      expect(output).toContain('useEffect');
      expect(output).toContain('[]');
    });

    test('watch → useEffect with deps', () => {
      const output = compileReact('page T:\n  state period: str = "week"\n  watch period:\n    loading = true');
      expect(output).toContain('useEffect');
      expect(output).toContain('[period]');
    });
  });

  describe('UI 요소', () => {
    test('text → span', () => {
      const output = compileReact('page T:\n  text "hello"');
      expect(output).toContain('<span');
      expect(output).toContain('hello');
    });

    test('text with size/bold', () => {
      const output = compileReact('page T:\n  text "제목" size=xl bold');
      expect(output).toContain('fontSize');
      expect(output).toContain('fontWeight');
    });

    test('text size=2xl → fontSize 32px', () => {
      const output = compileReact('page T:\n  text "title" size=2xl');
      expect(output).toContain("fontSize: '32px'");
    });

    test('text size=3xl → fontSize 40px', () => {
      const output = compileReact('page T:\n  text "big" size=3xl');
      expect(output).toContain("fontSize: '40px'");
    });

    test('text size=xs → fontSize 12px', () => {
      const output = compileReact('page T:\n  text "small" size=xs');
      expect(output).toContain("fontSize: '12px'");
    });

    test('text size=lg → fontSize 20px', () => {
      const output = compileReact('page T:\n  text "medium" size=lg');
      expect(output).toContain("fontSize: '20px'");
    });

    test('button → button tag', () => {
      const output = compileReact('page T:\n  state count: int = 0\n  button "+1" -> count += 1');
      expect(output).toContain('<button');
      expect(output).toContain('onClick');
      expect(output).toContain('+1');
    });

    test('input → controlled input', () => {
      const output = compileReact('page T:\n  state name: str = ""\n  input name placeholder="입력"');
      expect(output).toContain('value={name}');
      expect(output).toContain('onChange');
      expect(output).toContain('placeholder="입력"');
    });

    test('toggle → checkbox input', () => {
      const output = compileReact('page T:\n  state active: bool = false\n  toggle active');
      expect(output).toContain('type="checkbox"');
      expect(output).toContain('checked');
    });

    test('image → img tag', () => {
      const output = compileReact('page T:\n  image src width=200');
      expect(output).toContain('<img');
    });

    test('link → a tag', () => {
      const output = compileReact('page T:\n  link "홈" href="/home"');
      expect(output).toContain('<a');
      expect(output).toContain('href');
    });
  });

  describe('layout', () => {
    test('layout row → flex div', () => {
      const output = compileReact('page T:\n  layout row gap=8:\n    text "hello"');
      expect(output).toContain('display');
      expect(output).toContain('flex');
      expect(output).toContain('row');
      expect(output).toContain("gap: '8px'");
    });

    test('layout col → flex column div', () => {
      const output = compileReact('page T:\n  layout col:\n    text "hello"');
      expect(output).toContain('column');
    });

    test('layout grid → grid div', () => {
      const output = compileReact('page T:\n  layout grid cols=3 gap=16:\n    text "hello"');
      expect(output).toContain('grid');
    });

    test('layout center → alignItems center', () => {
      const output = compileReact('page T:\n  layout row center:\n    text "hello"');
      expect(output).toContain('center');
    });
  });

  describe('제어 흐름', () => {
    test('if → 조건부 렌더링', () => {
      const output = compileReact('page T:\n  state loading: bool = true\n  if loading:\n    text "로딩..."');
      expect(output).toContain('{loading && (');
    });

    test('if-else', () => {
      const output = compileReact('page T:\n  state loading: bool = true\n  if loading:\n    text "로딩..."\n  else:\n    text "완료"');
      expect(output).toContain('loading');
      expect(output).toContain('로딩...');
      expect(output).toContain('완료');
    });

    test('for → map', () => {
      const output = compileReact('page T:\n  state items: list[str] = []\n  for item in items:\n    text item');
      expect(output).toContain('.map(');
      expect(output).toContain('item');
    });
  });

  describe('check 변환', () => {
    test('check → runtime assertion', () => {
      const output = compileReact('page T:\n  state items: list[str] = []\n  check items.length <= 100 "100개 초과 불가"');
      expect(output).toContain('100개 초과 불가');
    });
  });

  describe('완전한 예제', () => {
    test('카운터 앱', () => {
      const source = `page Counter:
  state count: int = 0
  derived doubled = count * 2

  fn increment():
    count += 1

  layout col gap=16:
    text "카운터" size=2xl bold
    text "{count}" size=3xl bold
    button "+1" style=primary -> increment()`;

      const output = compileReact(source);
      expect(output).toContain('useState(0)');
      expect(output).toContain('useMemo');
      expect(output).toContain('increment');
      expect(output).toContain('<button');
      expect(output).toContain('onClick');
    });
  });
});
