import { describe, test, expect } from 'vitest';
import { compile } from '../../src/compiler.js';

function compileSvelte(source: string): string {
  return compile(source, { target: 'svelte' }).code;
}

describe('Svelte Code Generator', () => {
  describe('기본 구조', () => {
    test('page → script + html', () => {
      const output = compileSvelte('page Empty:');
      expect(output).toContain('// Generated by 0x');
      // Empty pages omit <script> section
      expect(output).not.toContain('<script>');
    });
  });

  describe('state 변환', () => {
    test('state → $state', () => {
      const output = compileSvelte('page T:\n  state count: int = 0');
      expect(output).toContain('let count = $state(0)');
    });

    test('state → $state (list)', () => {
      const output = compileSvelte('page T:\n  state items: list[str] = []');
      expect(output).toContain('let items = $state([])');
    });
  });

  describe('derived 변환', () => {
    test('derived → $derived', () => {
      const output = compileSvelte('page T:\n  state a: int = 1\n  derived total = a + 1');
      expect(output).toContain('$derived');
      expect(output).toContain('total');
    });
  });

  describe('라이프사이클', () => {
    test('on mount → onMount', () => {
      const output = compileSvelte('page T:\n  on mount:\n    loading = false');
      expect(output).toContain('onMount');
    });
  });

  describe('UI 요소', () => {
    test('text → span', () => {
      const output = compileSvelte('page T:\n  text "hello"');
      expect(output).toContain('<span');
      expect(output).toContain('hello');
    });

    test('text size=2xl → font-size: 32px', () => {
      const output = compileSvelte('page T:\n  text "title" size=2xl');
      expect(output).toContain('font-size: 32px');
    });

    test('text size=xs → font-size: 12px', () => {
      const output = compileSvelte('page T:\n  text "small" size=xs');
      expect(output).toContain('font-size: 12px');
    });

    test('text color unquoted in CSS', () => {
      const output = compileSvelte('page T:\n  text "hi" color=#333');
      expect(output).toContain('color: #333');
      expect(output).not.toContain("color: '#333'");
    });

    test('button → onclick', () => {
      const output = compileSvelte('page T:\n  state count: int = 0\n  button "+1" -> count += 1');
      expect(output).toContain('<button');
      expect(output).toContain('onclick');
    });

    test('input → bind:value', () => {
      const output = compileSvelte('page T:\n  state name: str = ""\n  input name placeholder="입력"');
      expect(output).toContain('bind:value');
    });
  });

  describe('제어 흐름', () => {
    test('if → {#if}', () => {
      const output = compileSvelte('page T:\n  state loading: bool = true\n  if loading:\n    text "로딩..."');
      expect(output).toContain('{#if');
      expect(output).toContain('{/if}');
    });

    test('for → {#each}', () => {
      const output = compileSvelte('page T:\n  state items: list[str] = []\n  for item in items:\n    text item');
      expect(output).toContain('{#each');
      expect(output).toContain('{/each}');
    });
  });

  describe('layout', () => {
    test('layout → div with style', () => {
      const output = compileSvelte('page T:\n  layout row gap=8:\n    text "hello"');
      expect(output).toContain('display: flex');
    });
  });
});
