import { describe, test, expect } from 'vitest';
import { compile } from '../../src/compiler.js';

function compileVue(source: string): string {
  return compile(source, { target: 'vue' }).code;
}

describe('Vue Code Generator', () => {
  describe('기본 구조', () => {
    test('page → script setup + template', () => {
      const output = compileVue('page Empty:');
      expect(output).toContain('// Generated by 0x');
      expect(output).toContain('<template>');
      // Empty pages omit <script setup> section
      expect(output).not.toContain('<script setup>');
    });
  });

  describe('state 변환', () => {
    test('state → ref', () => {
      const output = compileVue('page T:\n  state count: int = 0');
      expect(output).toContain('const count = ref(0)');
      expect(output).toContain("import { ref");
    });

    test('state → ref (str)', () => {
      const output = compileVue("page T:\n  state name: str = \"\"");
      expect(output).toContain("const name = ref('')");
    });

    test('state → ref (list)', () => {
      const output = compileVue('page T:\n  state items: list[str] = []');
      expect(output).toContain('const items = ref([])');
    });
  });

  describe('derived 변환', () => {
    test('derived → computed', () => {
      const output = compileVue('page T:\n  state a: int = 1\n  derived total = a + 1');
      expect(output).toContain('computed');
      expect(output).toContain('total');
    });
  });

  describe('라이프사이클', () => {
    test('on mount → onMounted', () => {
      const output = compileVue('page T:\n  on mount:\n    loading = false');
      expect(output).toContain('onMounted');
    });

    test('watch → watch', () => {
      const output = compileVue('page T:\n  state period: str = "week"\n  watch period:\n    loading = true');
      expect(output).toContain('watch(');
      expect(output).toContain('period');
    });
  });

  describe('UI 요소', () => {
    test('text → span', () => {
      const output = compileVue('page T:\n  text "hello"');
      expect(output).toContain('<span');
      expect(output).toContain('hello');
    });

    test('text size=2xl → font-size: 32px', () => {
      const output = compileVue('page T:\n  text "title" size=2xl');
      expect(output).toContain('font-size: 32px');
    });

    test('text size=xs → font-size: 12px', () => {
      const output = compileVue('page T:\n  text "small" size=xs');
      expect(output).toContain('font-size: 12px');
    });

    test('text color unquoted in CSS', () => {
      const output = compileVue('page T:\n  text "hi" color=#333');
      expect(output).toContain('color: #333');
      expect(output).not.toContain("color: '#333'");
    });

    test('button → @click', () => {
      const output = compileVue('page T:\n  state count: int = 0\n  button "+1" -> count += 1');
      expect(output).toContain('<button');
      expect(output).toContain('@click');
    });

    test('input → v-model', () => {
      const output = compileVue('page T:\n  state name: str = ""\n  input name placeholder="입력"');
      expect(output).toContain('v-model');
    });
  });

  describe('제어 흐름', () => {
    test('if → v-if', () => {
      const output = compileVue('page T:\n  state loading: bool = true\n  if loading:\n    text "로딩..."');
      expect(output).toContain('v-if');
    });

    test('for → v-for', () => {
      const output = compileVue('page T:\n  state items: list[str] = []\n  for item in items:\n    text item');
      expect(output).toContain('v-for');
    });
  });

  describe('layout', () => {
    test('layout → div with flex', () => {
      const output = compileVue('page T:\n  layout row gap=8:\n    text "hello"');
      expect(output).toContain('display: flex');
      expect(output).toContain('row');
    });
  });
});
